id: P006735
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN3480
  title: སྐར་རྩིས་ཀྱི་ལག་ལེན་བྱེད་གྲུབ་སྒང་དྲིལ་ལྟར་བཀོད་པ།
  author: ''
  volumes:
    29d5e8cd904d4c50a2ebbc344be30356:
      image_group_id: I3CN8749
      title: ''
      volume_number: 1
      total_pages: 482
      base_file: v001.txt
