id: P006735
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 12:20:03.506825
source_metadata:
  id: bdr:W3CN3480
  title: སྐར་རྩིས་ཀྱི་ལག་ལེན་བྱེད་གྲུབ་སྒང་དྲིལ་ལྟར་བཀོད་པ།
  author: ''
  volumes:
    29d5e8cd904d4c50a2ebbc344be30356:
      image_group_id: I3CN8749
      title: ''
      volume_number: 1
      total_pages: 482
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
